server:
  port: 8080
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-server:9000/oauth2/default
      client:
        registration:
          keycloak:
            client-id: login-app
            authorization-grant-type: authorization_code
            scope: openid
        provider:
          keycloak:
            issuer-uri: https://localhost:8080/auth/realms/test
            token-uri: https://localhost:8080/auth/realms/dev/protocol/openid-connect/token
